export const mockEmployees = [
  {
    id: 'emp-101',
    employeeId: 'DF-101',
    name: 'Sarah Jenkins',
    email: 'sarah.jenkins@dayflow.io',
    phone: '+1 (555) 234-5678',
    department: 'Engineering',
    team: 'Frontend Platform',
    designation: 'Senior Staff Engineer',
    manager: 'David Miller',
    joiningDate: '2023-01-15',
    status: 'active',
    address: '742 Evergreen Terrace, San Francisco, CA',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    salary: 135000,
    role: 'employee',
  },
  {
    id: 'emp-102',
    employeeId: 'DF-102',
    name: 'Marcus Vance',
    email: 'marcus.vance@dayflow.io',
    phone: '+1 (555) 345-6789',
    department: 'Human Resources',
    team: 'People Operations',
    designation: 'HR Lead & Talent Director',
    manager: 'Executive Board',
    joiningDate: '2022-03-10',
    status: 'active',
    address: '120 Market St, San Francisco, CA',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    salary: 145000,
    role: 'hr',
  },
  {
    id: 'emp-103',
    employeeId: 'DF-103',
    name: 'Elena Rostova',
    email: 'elena.rostova@dayflow.io',
    phone: '+1 (555) 456-7890',
    department: 'Product Design',
    team: 'UX Research & Design',
    designation: 'Lead UI/UX Designer',
    manager: 'Sarah Jenkins',
    joiningDate: '2023-06-01',
    status: 'active',
    address: '450 Sunset Blvd, Los Angeles, CA',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
    salary: 120000,
    role: 'employee',
  },
  {
    id: 'emp-104',
    employeeId: 'DF-104',
    name: 'Kenji Sato',
    email: 'kenji.sato@dayflow.io',
    phone: '+1 (555) 567-8901',
    department: 'Engineering',
    team: 'Cloud Infrastructure',
    designation: 'DevOps Architect',
    manager: 'David Miller',
    joiningDate: '2022-11-20',
    status: 'active',
    address: '88 Tech Way, Austin, TX',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    salary: 140000,
    role: 'employee',
  },
  {
    id: 'emp-105',
    employeeId: 'DF-105',
    name: 'Amira Patel',
    email: 'amira.patel@dayflow.io',
    phone: '+1 (555) 678-9012',
    department: 'Marketing',
    team: 'Growth & Brand',
    designation: 'Product Marketing Manager',
    manager: 'Rachel Green',
    joiningDate: '2023-08-14',
    status: 'active',
    address: '300 Pine St, Seattle, WA',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    salary: 110000,
    role: 'employee',
  },
  {
    id: 'emp-106',
    employeeId: 'DF-106',
    name: 'David Miller',
    email: 'david.miller@dayflow.io',
    phone: '+1 (555) 789-0123',
    department: 'Engineering',
    team: 'Core Backend',
    designation: 'Engineering VP',
    manager: 'Executive Board',
    joiningDate: '2021-05-10',
    status: 'active',
    address: '500 Silicon Ave, Palo Alto, CA',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    salary: 180000,
    role: 'employee',
  }
];

export const mockCurrentUserEmployee = mockEmployees[0];
export const mockCurrentUserHR = mockEmployees[1];

export const mockAttendanceRecords = [
  {
    id: 'att-1',
    employeeId: 'DF-101',
    employeeName: 'Sarah Jenkins',
    department: 'Engineering',
    date: '2026-08-22',
    checkIn: '09:02 AM',
    checkOut: '05:45 PM',
    hours: '8.7',
    status: 'present',
    lateMinutes: 2,
    overtimeMinutes: 45,
  },
  {
    id: 'att-2',
    employeeId: 'DF-101',
    employeeName: 'Sarah Jenkins',
    department: 'Engineering',
    date: '2026-08-21',
    checkIn: '08:58 AM',
    checkOut: '05:30 PM',
    hours: '8.5',
    status: 'present',
    lateMinutes: 0,
    overtimeMinutes: 30,
  },
  {
    id: 'att-3',
    employeeId: 'DF-101',
    employeeName: 'Sarah Jenkins',
    department: 'Engineering',
    date: '2026-08-20',
    checkIn: '09:25 AM',
    checkOut: '06:00 PM',
    hours: '8.5',
    status: 'late',
    lateMinutes: 25,
    overtimeMinutes: 0,
  },
  {
    id: 'att-4',
    employeeId: 'DF-103',
    employeeName: 'Elena Rostova',
    department: 'Product Design',
    date: '2026-08-22',
    checkIn: '09:15 AM',
    checkOut: '—',
    hours: '3.2',
    status: 'present',
    lateMinutes: 15,
    overtimeMinutes: 0,
  },
  {
    id: 'att-5',
    employeeId: 'DF-104',
    employeeName: 'Kenji Sato',
    department: 'Engineering',
    date: '2026-08-22',
    checkIn: '—',
    checkOut: '—',
    hours: '0.0',
    status: 'absent',
    lateMinutes: 0,
    overtimeMinutes: 0,
  },
  {
    id: 'att-6',
    employeeId: 'DF-105',
    employeeName: 'Amira Patel',
    department: 'Marketing',
    date: '2026-08-22',
    checkIn: '—',
    checkOut: '—',
    hours: '0.0',
    status: 'leave',
    lateMinutes: 0,
    overtimeMinutes: 0,
  }
];

export const mockLeaveRequests = [
  {
    id: 'lv-01',
    employeeId: 'DF-101',
    employeeName: 'Sarah Jenkins',
    department: 'Engineering',
    leaveType: 'Annual Leave',
    startDate: '2026-09-01',
    endDate: '2026-09-05',
    days: 5,
    reason: 'Family vacation and personal downtime.',
    status: 'pending',
    appliedAt: '2026-08-20',
  },
  {
    id: 'lv-02',
    employeeId: 'DF-103',
    employeeName: 'Elena Rostova',
    department: 'Product Design',
    leaveType: 'Sick Leave',
    startDate: '2026-08-15',
    endDate: '2026-08-16',
    days: 2,
    reason: 'Severe seasonal flu with medical rest advice.',
    status: 'approved',
    appliedAt: '2026-08-14',
  },
  {
    id: 'lv-03',
    employeeId: 'DF-104',
    employeeName: 'Kenji Sato',
    department: 'Engineering',
    leaveType: 'Casual Leave',
    startDate: '2026-08-28',
    endDate: '2026-08-28',
    days: 1,
    reason: 'Home utility maintenance and inspection.',
    status: 'pending',
    appliedAt: '2026-08-21',
  },
  {
    id: 'lv-04',
    employeeId: 'DF-105',
    employeeName: 'Amira Patel',
    department: 'Marketing',
    leaveType: 'Emergency Leave',
    startDate: '2026-08-22',
    endDate: '2026-08-23',
    days: 2,
    reason: 'Urgent family matter requiring immediate travel.',
    status: 'approved',
    appliedAt: '2026-08-21',
  }
];

export const mockLeaveBalances = {
  casual: { total: 12, used: 3, available: 9 },
  sick: { total: 10, used: 2, available: 8 },
  annual: { total: 20, used: 6, available: 14 },
  emergency: { total: 5, used: 1, available: 4 },
};

export const mockPayrolls = [
  {
    id: 'pr-2026-07-101',
    employeeId: 'DF-101',
    employeeName: 'Sarah Jenkins',
    department: 'Engineering',
    month: 'July',
    year: 2026,
    basicSalary: 9500,
    allowances: 1200,
    bonus: 800,
    overtime: 350,
    deductions: 600,
    netSalary: 11250,
    status: 'paid',
    paymentDate: '2026-07-31',
    tax: 1800,
    providentFund: 450,
  },
  {
    id: 'pr-2026-06-101',
    employeeId: 'DF-101',
    employeeName: 'Sarah Jenkins',
    department: 'Engineering',
    month: 'June',
    year: 2026,
    basicSalary: 9500,
    allowances: 1200,
    bonus: 0,
    overtime: 200,
    deductions: 600,
    netSalary: 10300,
    status: 'paid',
    paymentDate: '2026-06-30',
    tax: 1650,
    providentFund: 450,
  },
  {
    id: 'pr-2026-07-103',
    employeeId: 'DF-103',
    employeeName: 'Elena Rostova',
    department: 'Product Design',
    month: 'July',
    year: 2026,
    basicSalary: 8500,
    allowances: 950,
    bonus: 500,
    overtime: 150,
    deductions: 450,
    netSalary: 9650,
    status: 'paid',
    paymentDate: '2026-07-31',
    tax: 1450,
    providentFund: 400,
  }
];

export const mockWellnessScores = [
  {
    employeeId: 'DF-101',
    employeeName: 'Sarah Jenkins',
    department: 'Engineering',
    score: 88,
    indicator: 'stable',
    attendancePercentage: 96,
    absenceCount: 1,
    leavePattern: 'Evenly distributed across quarters',
    trend: '+2% over last 30 days',
    explanation: 'Attendance has remained consistently steady. Regular punch-in habits observed with balanced leave distribution.',
    history: [
      { month: 'Mar', score: 85 },
      { month: 'Apr', score: 87 },
      { month: 'May', score: 86 },
      { month: 'Jun', score: 89 },
      { month: 'Jul', score: 87 },
      { month: 'Aug', score: 88 },
    ]
  },
  {
    employeeId: 'DF-104',
    employeeName: 'Kenji Sato',
    department: 'Engineering',
    score: 62,
    indicator: 'monitor',
    attendancePercentage: 78,
    absenceCount: 4,
    leavePattern: 'Cluster of Monday absences noted',
    trend: '-14% over last 30 days',
    explanation: 'Attendance declined from 92% to 78% during the recent period with repeated sudden unscheduled absences on Mondays.',
    history: [
      { month: 'Mar', score: 90 },
      { month: 'Apr', score: 88 },
      { month: 'May', score: 82 },
      { month: 'Jun', score: 75 },
      { month: 'Jul', score: 68 },
      { month: 'Aug', score: 62 },
    ]
  },
  {
    employeeId: 'DF-105',
    employeeName: 'Amira Patel',
    department: 'Marketing',
    score: 48,
    indicator: 'needs_attention',
    attendancePercentage: 69,
    absenceCount: 6,
    leavePattern: 'Consecutive sudden leave patterns',
    trend: '-22% over last 30 days',
    explanation: 'High volume of short-notice absences and frequent late arrivals recorded in the past 4 weeks.',
    history: [
      { month: 'Mar', score: 88 },
      { month: 'Apr', score: 82 },
      { month: 'May', score: 74 },
      { month: 'Jun', score: 65 },
      { month: 'Jul', score: 54 },
      { month: 'Aug', score: 48 },
    ]
  }
];

export const mockSmartAlerts = [
  {
    id: 'alt-01',
    severity: 'high',
    title: 'Attendance Decline Alert',
    message: 'Attendance for Amira Patel declined from 92% to 69% in the last 30 days.',
    target: 'Amira Patel (Marketing)',
    employeeId: 'DF-105',
    date: '2026-08-21',
    status: 'open',
    type: 'attendance_decline',
  },
  {
    id: 'alt-02',
    severity: 'medium',
    title: 'Repeated Monday Absences',
    message: 'Kenji Sato has recorded 3 unscheduled absences on Mondays over the past 5 weeks.',
    target: 'Kenji Sato (Engineering)',
    employeeId: 'DF-104',
    date: '2026-08-20',
    status: 'open',
    type: 'repeated_absences',
  },
  {
    id: 'alt-03',
    severity: 'medium',
    title: 'High Leave Concentration Alert',
    message: '3 out of 5 Engineers in Frontend Platform requested leave for the same week (Sep 1 - Sep 5).',
    target: 'Frontend Platform Team',
    employeeId: null,
    date: '2026-08-19',
    status: 'acknowledged',
    type: 'reduced_team_availability',
  },
  {
    id: 'alt-04',
    severity: 'low',
    title: 'Late Arrival Pattern',
    message: 'Elena Rostova logged 4 late check-ins (>15 min) in the preceding 10 work days.',
    target: 'Elena Rostova (Design)',
    employeeId: 'DF-103',
    date: '2026-08-18',
    status: 'resolved',
    type: 'late_arrival_pattern',
  }
];

export const mockNotifications = [
  {
    id: 'notif-1',
    title: 'Leave Request Approved',
    message: 'Your leave request for Sep 1 – Sep 5 has been reviewed and approved by HR.',
    type: 'leave_approved',
    timestamp: '10 minutes ago',
    read: false,
    link: '/employee/leave',
  },
  {
    id: 'notif-2',
    title: 'July Payslip Ready',
    message: 'Your payslip for July 2026 is now available for download.',
    type: 'payroll_updated',
    timestamp: '2 hours ago',
    read: false,
    link: '/employee/payroll',
  },
  {
    id: 'notif-3',
    title: 'Smart HR Alert Triggered',
    message: 'New High severity alert created: Attendance Decline for Amira Patel.',
    type: 'smart_alert',
    timestamp: 'Yesterday',
    read: true,
    link: '/hr/alerts',
  },
  {
    id: 'notif-4',
    title: 'Company Policy Update',
    message: 'The annual holiday calendar for Q4 2026 has been published.',
    type: 'system',
    timestamp: '3 days ago',
    read: true,
    link: '/employee/dashboard',
  }
];

export const mockAuditActivities = [
  {
    id: 'act-1',
    actor: 'Marcus Vance (HR Lead)',
    action: 'Approved leave request for Sarah Jenkins (Sep 1 - Sep 5).',
    timestamp: 'Today at 10:45 AM',
    badge: 'Leave',
  },
  {
    id: 'act-2',
    actor: 'System Automation',
    action: 'Generated monthly payroll records for 48 active employees.',
    timestamp: 'Today at 09:00 AM',
    badge: 'Payroll',
  },
  {
    id: 'act-3',
    actor: 'Marcus Vance (HR Lead)',
    action: 'Acknowledged Smart Alert: Team availability risk in Frontend Platform.',
    timestamp: 'Yesterday at 04:15 PM',
    badge: 'Alerts',
  },
  {
    id: 'act-4',
    actor: 'Sarah Jenkins',
    action: 'Updated emergency contact information and address.',
    timestamp: 'Aug 20, 2026 at 02:30 PM',
    badge: 'Profile',
  }
];

export const mockAnalyticsData = {
  attendanceTrend: [
    { day: 'Mon', attendanceRate: 95, lateRate: 4 },
    { day: 'Tue', attendanceRate: 98, lateRate: 2 },
    { day: 'Wed', attendanceRate: 96, lateRate: 3 },
    { day: 'Thu', attendanceRate: 92, lateRate: 6 },
    { day: 'Fri', attendanceRate: 89, lateRate: 8 },
  ],
  departmentHeadcount: [
    { name: 'Engineering', count: 32 },
    { name: 'Product & Design', count: 12 },
    { name: 'Marketing & Sales', count: 18 },
    { name: 'HR & Ops', count: 8 },
    { name: 'Support', count: 14 },
  ],
  leaveDistribution: [
    { name: 'Annual', value: 45 },
    { name: 'Casual', value: 25 },
    { name: 'Sick', value: 20 },
    { name: 'Emergency', value: 10 },
  ],
  wellnessDistribution: [
    { name: 'Stable (🟢)', value: 72, color: '#16a34a' },
    { name: 'Monitor (🟡)', value: 20, color: '#d97706' },
    { name: 'Needs Attention (🔴)', value: 8, color: '#dc2626' },
  ],
  monthlyPayrollTrend: [
    { month: 'Feb', amount: 380000 },
    { month: 'Mar', amount: 395000 },
    { month: 'Apr', amount: 410000 },
    { month: 'May', amount: 420000 },
    { month: 'Jun', amount: 435000 },
    { month: 'Jul', amount: 448000 },
  ]
};
